const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const ts = require('../OMS_Frontend/node_modules/typescript');
const source = fs.readFileSync('OMS_Frontend/src/app/manage-user/manage-users.component.ts', 'utf8');
const compiled = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.CommonJS, experimentalDecorators: true }}).outputText;
const sandbox = { exports: {}, setTimeout: () => {}, require: () => new Proxy({}, { get: (_, key) => key === 'inject' ? () => ({ detectChanges() {} }) : () => () => {} }) };
vm.runInNewContext(compiled, sandbox);
let requests = [];
const http = { patch: (url, body) => { requests.push({url, body}); return { subscribe() {} }; } };
const component = new sandbox.exports.ManageUsersComponent(http, { isSuperAdmin: () => true }, {});
const user = (id, firstName, createdDate, extra = {}) => ({ id, firstName, lastName: 'User', createdDate, roleId: null, role: 'No Role', status: 'Pending', isActive: false, isDeleted: false, ...extra });
const older = user(2, 'Zara', '2026-09-01');
const newer = user(3, 'Ali', '2026-09-22');
component.users = [older, user(1, 'Admin', '2026-09-23', {roleId: 1}), newer];
component.applyFilters();
assert.equal(component.filteredUsers[0].id, 3, 'New registrations appear first');
component.sort('fullName');
assert.equal(component.filteredUsers[0].firstName, 'Ali');
component.sort('fullName');
assert.equal(component.filteredUsers[0].firstName, 'Zara');
component.pageSize = 1;
assert.equal(component.paginatedUsers.length, 1);
component.selectUserStatus(newer, 'Approved');
assert.equal(component.approvalRoleId, null);
component.confirmToggleActive();
assert.equal(requests.length, 0, 'Approval without a role never calls API');
assert.match(component.statusError, /Select a role/);
component.approvalRoleId = 3;
component.confirmToggleActive();
assert.equal(requests[0].body.roleId, 3);
assert.equal(requests[0].body.status, 'Approved');
component.saving = false;
component.selectUserStatus(older, 'Rejected');
assert.equal(component.approvalRoleId, null, 'Selection is reset between users');
component.confirmToggleActive();
assert.equal(requests[1].body.status, 'Rejected');
assert.equal(requests[1].body.roleId, null);
component.saving = false;
component.closeModals();
component.selectUserStatus(user(4, 'Deleted', '2026-09-22', {isDeleted: true}), 'Approved');
assert.equal(component.showToggleActiveModal, false);
component.searchTerm = 'pending';
component.applyFilters();
assert.equal(component.filteredUsers.length, 2);
console.log('PASS: newest-first ordering, name sorting both ways, pagination, mandatory role, approval payload, rejection, role reset, deleted-user guard, status search');
